[build]
    publish = "public/"
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-gatsby"

[[plugins]]
    package = "@netlify/plugin-lighthouse"

[[redirects]]
    from = "https://micha149s-website.netlify.app/"
    to = "https://michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://van-engelshoven.de/"
    to = "https://michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://www.van-engelshoven.de/"
    to = "https://michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://www.michael-van-engelshoven.de/"
    to = "https://michael-van-engelshoven.de"
    status = 301
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' 'unsafe-inline'; img-src 'self' data:"
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin"
        Permissions-Policy = "camera=(), geolocation=(), microphone=()"
