[build]
    publish = "public/"
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-gatsby"

[[plugins]]
    package = "@netlify/plugin-lighthouse"

[[redirects]]
    from = "https://micha149s-website.netlify.app/"
    to = "https://www.michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://van-engelshoven.de/"
    to = "https://www.michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://www.van-engelshoven.de/"
    to = "https://www.michael-van-engelshoven.de"
    status = 301
    force = true

[[redirects]]
    from = "https://michael-van-engelshoven.de/"
    to = "https://www.michael-van-engelshoven.de"
    status = 301
    force = true
